src/Projeto/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

# importando views da aplicação core
from core.views import IndexView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('conta/', include('django.contrib.auth.urls')),
    path('', include('core.urls')),
    path('amigos/', include('amigos.urls')),
    path('itens/', include('itens.urls')),
    path('avaliacoes/', include('avaliacoes.urls')),
    path('comentario/', include('comentarios.urls'))

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = 'Critic Hub'
admin.site.site_header = 'Admin Critic Hub'
admin.site.index_title = 'Administração Critic Hub'

src/core/urls.py
from django.urls import path

# from .views import cadastro, index, v404, v500, carregar_cidades
from .views import *

urlpatterns = [
    path('', index, name='index'),
    path('cadastro', cadastro, name='cadastro'),
    path('404', v404, name='v404'),
    path('500', v500, name='v500'),

    path('minha_conta', minha_conta, name='minha_conta'),
    path('usuario/<int:pk>', user_view, name='usuario'),
    path('excluir_conta/<int:user_id>', excluir_conta, name='excluir_conta'),

    path('busca/<str:app_name>', searchbar, name='searchbar'),

    path('ajax/get-cidades-ajax/', carregar_cidades, name='get-cidades-ajax'),
]

src/itens/urls.py
from django.urls import path

from .views import *

urlpatterns = [
    path('<str:tipo_item>/<int:pk>', item, name="item"),
    path('<str:tipo_item>/', itens, name='itens'),

    path('<str:app_name>/cadastrar', cadastrar_item, name="cadastro_item"),

    path('validar_itens/<str:tipo_item>', validar_itens, name="validar_itens"),
]

src/itens/models.py
from datetime import datetime

from django.db import models
from core.models import Usuario

from django.db.models import signals
from django.db.models.deletion import SET_NULL
from django.template.defaultfilters import slugify
from django.urls.base import reverse
from django.core.validators import MinValueValidator, MaxValueValidator
from stdimage.models import StdImageField

class CategoriaItem(models.Model):
    categoria = models.CharField("Categoria", max_length=255)

    def __str__(self):
        return self.categoria

class Itens(models.Model):
    data_criacao = models.DateField("Data de Criação", auto_now_add=True)
    data_atualizacao = models.DateField("Data de Atualização", auto_now=True)
    user_id = models.ForeignKey(Usuario, on_delete=models.CASCADE, verbose_name="user_id", null=True)
    titulo = models.CharField("Título", max_length=100, unique=True)
    pais = models.CharField("Pais", max_length=100)
    ano_lancamento = models.IntegerField("Ano de Lançamento", default=datetime.now().year, validators=[MinValueValidator(1500), MaxValueValidator(datetime.now().year)])
    slug = models.SlugField("Slug", max_length=100, editable=False, unique=False)
    imagem = StdImageField("Imagem de capa", null=True, blank=True, upload_to='itens', variations={'thumbnail': (300, 300)})
    ativo = models.BooleanField("Ativo", default=False)
    categoria = models.ForeignKey(CategoriaItem, verbose_name="Categoria", on_delete=SET_NULL, null=True)
    tipo_item = models.CharField("Tipo", max_length=100, default='filme')

    class Meta:
        abstract = True
    
    def aprovar_item(self, user):
        if user.is_superuser:
            self.ativo = True
            self.save()
    
    def excluir_item(self, user):
        if user.is_superuser:
            self.delete()
    
    def revisar_item(self, user):
        pass

    def get_item_values(self):
        vals = {
            'titulo': self.titulo,
            'pais': self.pais,
            'ano_lancamento': self.ano_lancamento,
            'ativo': self.ativo
        }
        return vals


class Livro(Itens):
    volume = models.PositiveSmallIntegerField("Volume")
    autor = models.CharField("Autor", max_length=100)
    editora = models.CharField("Editora", max_length=100)

    def get_absolute_url(self):
        return reverse("itens:livro", kwargs={'pk': self.pk})
    
    def get_item_values(self):
        vals = super().get_item_values()
        vals.update({
            'volume': self.volume,
            'autor': self.autor,
            'editora': self.editora,
        })
        return vals

class Filme(Itens):
    volume = models.PositiveSmallIntegerField("Volume", null=True)
    diretor = models.CharField("Diretor", max_length=100)
    elenco = models.TextField("Elenco")

    def get_absolute_url(self):
        return reverse("itens:filme", kwargs={'pk': self.pk})
    
    def get_item_values(self):
        vals = super().get_item_values()
        vals.update({
            'volume': self.volume,
            'diretor': self.diretor,
            'elenco': self.elenco,
        })
        return vals

class Serie(Itens):
    qtd_temporadas = models.PositiveSmallIntegerField("Número de temporadas")
    diretor = models.CharField("Diretor", max_length=100)
    elenco = models.TextField("Elenco")

    def get_absolute_url(self):
        return reverse("itens:serie", kwargs={'pk': self.pk})
    
    def get_item_values(self):
        vals = super().get_item_values()
        vals.update({
            'qtd_temporadas': self.qtd_temporadas,
            'diretor': self.diretor,
            'elenco': self.elenco,
        })
        return vals

def pre_save_itens(signal, instance, sender, **kwargs):
    instance.slug = slugify(instance.titulo)

signals.pre_save.connect(pre_save_itens, sender=Itens)

src/itens/forms.py
from django import forms

from .models import Filme, Serie, Livro
    
class CadastroFilme(forms.ModelForm):
    class Meta:
        model = Filme
        fields = ['titulo', 'diretor', 'elenco', 'pais', 'ano_lancamento', 'imagem', 'categoria', 'tipo_item']

class CadastroSerie(forms.ModelForm):
    class Meta:
        model = Serie
        fields = ['titulo', 'diretor', 'elenco', 'pais', 'ano_lancamento', 'qtd_temporadas', 'imagem', 'categoria', 'tipo_item']   

class CadastroLivro(forms.ModelForm):
    class Meta:
        model = Livro
        fields = ['titulo', 'volume', 'autor', 'editora', 'pais', 'ano_lancamento', 'imagem', 'categoria', 'tipo_item']                

src/itens/views.py
from datetime import datetime
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib import messages

from .models import *
from .forms import CadastroFilme, CadastroSerie, CadastroLivro

from core.backend import bloquear_acesso, bloquear_acesso_admin
from core.models import Usuario

@bloquear_acesso
def item(request, tipo_item, pk):
    context = {}
    context['app_name'] = tipo_item

    if tipo_item == 'filme':
        obj_class = Filme
        obj_name = 'Filme'
        plural_obj_name = 'Filmes'
        search_params = ('titulo', 'pais', 'diretor')

    elif tipo_item == 'livro':
        obj_class = Livro
        obj_name = 'Livro'
        plural_obj_name = 'Livros'
        search_params = ('titulo', 'pais', 'autor')

    elif tipo_item == 'serie':
        obj_class = Serie
        obj_name = 'Série'
        plural_obj_name = 'Séries'
        search_params = ('titulo', 'pais', 'diretor')
    
    obj = get_object_or_404(obj_class, id=pk)

    context.update({
        'obj': obj,
        'obj_name': obj_name,
        'plural_obj_name': plural_obj_name,

        'search_filters': search_params,
    })
    return render(request, 'item.html', context)


@bloquear_acesso
def itens(request, tipo_item):
    #import pdb; pdb.set_trace()
    context = {}
    context['app_name'] = tipo_item

    if tipo_item == 'filme':
        obj_class = Filme
        obj_name = 'Filme'
        plural_obj_name = 'Filmes'
        search_params = ('titulo', 'pais', 'diretor')

    elif tipo_item == 'livro':
        obj_class = Livro
        obj_name = 'Livro'
        plural_obj_name = 'Livros'
        search_params = ('titulo', 'pais', 'autor')

    elif tipo_item == 'serie':
        obj_class = Serie
        obj_name = 'Série'
        plural_obj_name = 'Séries'
        search_params = ('titulo', 'pais', 'diretor')

    objs = obj_class.objects.filter(ativo=True)
    
    objs_add_recentemente = objs.order_by('-data_atualizacao')
   
    cont=0
    objs_add_recentemente_list= []

    for obj in objs_add_recentemente:
        if cont<=6:
            objs_add_recentemente_list.append(obj)
            cont+=1    

    context.update({
        'objs': objs,
        'objs_add_recentemente': objs_add_recentemente,
        'objs_indicados': [],

        'obj_name': obj_name,
        'plural_obj_name': plural_obj_name,

        'search_filters': search_params,
        'len_resultados': len(objs),
    })

    return render(request, 'itens.html', context)


def cadastrar_item(request, app_name):
    context = {}
    context['app_name'] = app_name
    context['categorias'] = CategoriaItem.objects.all()

    """status_message = False
    if 'status_message' in request.session:
        del request.session['status_message']"""

    if app_name == 'filme':
        form = CadastroFilme()
        obj_name = 'Filme'
    elif app_name == 'livro':
        form = CadastroLivro()
        obj_name = 'Livro'
    elif app_name == 'serie':
        form = CadastroSerie()
        obj_name = 'Série'
    else:
        return redirect('')

    context['obj_name'] = obj_name
   
    if request.method == 'POST':
        if app_name == 'filme':
            form = CadastroFilme(request.POST, request.FILES)
        elif app_name == 'livro':
            form = CadastroLivro(request.POST, request.FILES)
        elif app_name == 'serie':
            form = CadastroSerie(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            status_message = "Cadastro Realizado com sucesso! O item cadastrado estará disponível após um administrador validar."
            request.session['status_message'] = status_message
            return redirect(f'/itens/{app_name}')
        

    context['form'] = form


    return render(request, 'cadastro_item.html', context)


@bloquear_acesso_admin
def validar_itens(request, tipo_item):
    context = {}
    context['app_name'] = tipo_item
    
    status_message = False

    user = Usuario.objects.get(pk=request.user.id)

    if tipo_item == 'filme':
        obj_class = Filme
        obj_name = 'Filme'
    elif tipo_item == 'livro':
        obj_class = Livro
        obj_name = 'Livro'
    elif tipo_item == 'serie':
        obj_class = Serie
        obj_name = 'Série'

    if request.method == 'POST':
        using_obj = obj_class.objects.get(pk=int(request.POST.get('item_id')))
        
        if 'aprovar_cadastro' in request.POST:
            using_obj.aprovar_item(user)
            status_message = "Cadastro foi aprovado com Sucesso!"

        elif 'excluir_cadastro' in request.POST:
            using_obj.excluir_item(user)
            status_message = "Cadastro foi Excluido!"

        elif 'revisar_cadastro' in request.POST:
            using_obj.revisar_item(user)
        
        context['status_message'] = status_message

    objects = obj_class.objects.filter(ativo=False)
    
    context.update({
        'objects': objects,
        'len_objects': len(objects),
        'obj_name': obj_name,
    })

    return render(request, 'validar_itens.html', context)

src/itens/templates/add_recentemente.html
{% load static %}
<h1 id="home" style="padding-top: 50px;">Adicionado Recentemente</h1>
  
    <div class="box">
      {% for obj in objs_add_recentemente %}
        {% if obj.tipo_item == 'filme' %}
        <a style="color: rgb(254, 247, 255); text-decoration: none; font-family: Georgia; font-size: 15px;" 
        href="{% url 'item' tipo_item=obj.tipo_item pk=obj.pk %}" >{{obj.titulo}}<br><img src= "/media/{{obj.imagem.thumbnail}}"/><br>Volume: {{obj.volume}}<br>Gênero: {{obj.categoria}}</a>     
        {% elif obj.tipo_item == 'livro' %}
        <a style="color: rgb(254, 247, 255); text-decoration: none; font-family: Georgia; font-size: 15px;" 
        href="{% url 'item' tipo_item=obj.tipo_item pk=obj.pk %}" >{{obj.titulo}}<br><img src= "/media/{{obj.imagem.thumbnail}}"/><br>Volume: {{obj.volume}}<br>Gênero: {{obj.categoria}}</a>     
        {% elif obj.tipo_item == 'serie' %}
        <a style="color: rgb(254, 247, 255); text-decoration: none; font-family: Georgia; font-size: 15px;" 
        href="{% url 'item' tipo_item=obj.tipo_item pk=obj.pk %}" >{{obj.titulo}}<br><img src= "/media/{{obj.imagem.thumbnail}}"/><br>Nº Temporadas: {{obj.qtd_temporadas}}<br>Gênero: {{obj.categoria}}</a>     
        {% endif %}   
      {% endfor %}               
    </div>

      

src/itens/templates/cadastro _livro.html
{% extends 'base_login.html' %}


{% load static %}

{% load bootstrap4 %}

{% block content %}
<div class="limiter" style="background-image: url({% static 'images/fundo.png' %})" >
	<div class="container-login100">
		<div class="wrap-login100">
			<div class="container">
			<form action="{% url 'cadastro' %}" method="post" autocomplete="off" enctype="multipart/form-data" class="login100-form validate-form form">
				{% csrf_token %}
				
				<span class="login100-form-title p-b-34 p-t-27">
					<img src="{% static 'images/logo_critichub2.png' %}" alt="" width="300" height="200">
				</span>

				<h2 style="text-align: center; color:white">Cadastro</h2>

				{% bootstrap_messages %}

				{% bootstrap_form form %}
				
				<div class="container-login100-form-btn">
				{% buttons %}
					<button type="submit" class="login100-form-btn btn btn-primary">
						<h2 style = font-family:Georgia;font-size:12px;>Cadastrar Conta</h2>
					</button>
				{% endbuttons %}
				</div>

			</form>
			</div>
		</div>
	</div>
</div>
<div id="dropDownSelect1"></div>

{% bootstrap_javascript jquery='full' %}

<script src=https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js></script>

{% endblock %}

src/itens/templates/cadastro_filme.html
<br><br><label for="id_titulo">Título:</label><br><input type="text" name="titulo" maxlength="100" required id="id_titulo" size="40"><br>
<label for="id_diretor">Diretor:</label><br><input type="text" name="diretor" maxlength="100" required id="id_diretor" size="40"><br>
<label for="id_elenco">Elenco:</label><br><textarea name="elenco" cols="40" rows="10" required id="id_elenco" ></textarea><br>
<label for="id_pais">Pais:</label><br><input type="text" name="pais" maxlength="100" required id="id_pais" size="40"><br>
<label for="id_ano_lancamento">Ano de Lançamento:</label><input type="number" name="ano_lancamento" value="2021" required id="id_ano_lancamento"><br>
<label for="id_volume">Volume:</label><input type="number" name="volume" value="1" required id="id_volume"><br>
<label for="id_categoria">Categoria:</label>
<select name="categoria" required id="id_categoria">
    {% for categoria in categorias %}<option value="{{categoria.id}}">{{categoria}}</option>{% endfor %}
</select><br>
<label for="id_imagem">Imagem de capa:</label><input type="file" name="imagem" accept="image/*" id="id_imagem"><br>
<select name="user_id" required id="id_user_id" style="display: none;">
    <option value="{{user.id}}" selected>{{user.username}}</option>
</select>
<label for="id_tipo_item" style="display: none;">Tipo Item:</label><br><input type="text" name="tipo_item" value="filme" maxlength="100" required id="id_tipo_item" size="40" style="display: none;"><br>

src/itens/templates/cadastro_item.html
{% extends 'base.html' %}

{% load static %}

{% load bootstrap4 %}

{% block content %}
<div class="wrapper">
  <section class="main-container">
	<div>

	<form class="cadastro-labels" action="{% url 'cadastro_item' app_name=app_name %}" method="post" autocomplete="off" enctype="multipart/form-data" class="login100-form validate-form form">
		{% csrf_token %}
		<br>
		<br>
		<h2 style="text-align: center; color:white">Cadastrar {{obj_name}}</h2>


		<fieldset class="fieldset_cadastrar">
			{% if app_name == 'filme' %}
			Filmes{% include 'cadastro_filme.html' %}

			{% elif app_name == 'livro' %}
			Livros{% include 'cadastro_livro.html' %}

			{% elif app_name == 'serie' %}
		    Séries{% include 'cadastro_serie.html' %}

			{% endif %}
        </fieldset>
		
		<div class="container-login100-form-btn">
			<button type="submit">
				<h2>Cadastrar</h2>
			</button>
		</div>

	</form>
	</div>
  </section>
</div>

<div id="dropDownSelect1"></div>

{% bootstrap_javascript jquery='full' %}

<script src=https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js></script>

{% endblock %}

src/itens/templates/cadastro_livro.html
<br><br><label for="id_titulo">Título:</label><br><input type="text" name="titulo" maxlength="100" required id="id_titulo" size="40"><br>
<label for="id_diretor">Diretor:</label><br><input type="text" name="diretor" maxlength="100" required id="id_diretor" size="40"><br>
<label for="id_elenco">Elenco:</label><br><textarea name="elenco" cols="40" rows="10" required id="id_elenco" ></textarea><br>
<label for="id_pais">Pais:</label><br><input type="text" name="pais" maxlength="100" required id="id_pais" size="40"><br>
<label for="id_ano_lancamento">Ano de Lançamento:</label><input type="number" name="ano_lancamento" value="2021" required id="id_ano_lancamento"><br>
<label for="id_volume">Volume:</label><input type="number" name="volume" value="1" required id="id_volume"><br>
<label for="id_categoria">Categoria:</label>
<select name="categoria" required id="id_categoria">
    {% for categoria in categorias %}<option value="{{categoria.id}}">{{categoria}}</option>{% endfor %}
</select><br>
<label for="id_imagem">Imagem de capa:</label><input type="file" name="imagem" accept="image/*" id="id_imagem"><br>
<select name="user_id" required id="id_user_id" style="display: none;">
    <option value="{{user.id}}" selected>{{user.username}}</option>
</select>
<label for="id_tipo_item" style="display: none;">Tipo Item:</label><br><input type="text" name="tipo_item" value="livro" maxlength="100" required id="id_tipo_item" size="40" style="display: none;"><br>

src/itens/templates/cadastro_serie.html
<br><br><label for="id_titulo">Título:</label><br><input type="text" name="titulo" maxlength="100" required id="id_titulo" size="40"><br>
<label for="id_diretor">Diretor:</label><br><input type="text" name="diretor" maxlength="100" required id="id_diretor" size="40"><br>
<label for="id_elenco">Elenco:</label><br><textarea name="elenco" cols="40" rows="10" required id="id_elenco" ></textarea><br>
<label for="id_pais">Pais:</label><br><input type="text" name="pais" maxlength="100" required id="id_pais" size="40"><br>
<label for="id_ano_lancamento">Ano de Lançamento:</label><input type="number" name="ano_lancamento" value="2021" required id="id_ano_lancamento"><br>
<label for="id_qtd_temporadas">Número de temporadas:</label><input type="number" name="qtd_temporadas" value="1" required id="id_qtd_temporadas"><br>
<label for="id_categoria">Categoria:</label>
<select name="categoria" required id="id_categoria">
    {% for categoria in categorias %}<option value="{{categoria.id}}">{{categoria}}</option>{% endfor %}
</select><br>
<label for="id_imagem">Imagem de capa:</label><input type="file" name="imagem" accept="image/*" id="id_imagem"><br>
<select name="user_id" required id="id_user_id" style="display: none;">
    <option value="{{user.id}}" selected>{{user.username}}</option>
</select>
<label for="id_tipo_item" style="display: none;">Tipo Item:</label><br><input type="text" name="tipo_item" value="serie" maxlength="100" required id="id_tipo_item" size="40" style="display: none;"><br>

src/itens/templates/filmes.html
{% extends 'base.html' %}
{% load static %}

<!-- TÍTULO -->
{% block title %}Critic Hub / Filmes{% endblock %}

<!-- BLOCK CONTENT PRINCIPAL-->
{% block content %}

<div class="wrapper">  
  <!-- MAIN CONTAINER -->
  <section class="main-container" >

    {% include 'base_header_section.html' %}

    {% include 'add_recentemente.html' %}

    {% include 'indicados_p_vc.html' %}

    <h1 id="tvShows">Filmes</h1>
    <div class="box">
      <a href=""><img src="https://github.com/carlosavilae/Netflix-Clone/blob/master/img/tv1.PNG?raw=true" alt=""></a>
      <a href=""><img src="https://github.com/carlosavilae/Netflix-Clone/blob/master/img/tv2.PNG?raw=true" alt=""></a>
      <a href=""><img src="https://github.com/carlosavilae/Netflix-Clone/blob/master/img/tv3.PNG?raw=true" alt=""></a>
      <a href=""><img src="https://github.com/carlosavilae/Netflix-Clone/blob/master/img/tv4.PNG?raw=true" alt=""></a>
      <a href=""><img src="https://github.com/carlosavilae/Netflix-Clone/blob/master/img/tv5.PNG?raw=true" alt=""></a>
      <a href=""><img src="https://github.com/carlosavilae/Netflix-Clone/blob/master/img/tv6.PNG?raw=true" alt=""></a>

      <a href=""><img src="https://github.com/carlosavilae/Netflix-Clone/blob/master/img/tv7.PNG?raw=true" alt=""></a>
      <a href=""><img src="https://github.com/carlosavilae/Netflix-Clone/blob/master/img/tv8.PNG?raw=true" alt=""></a>
      <a href=""><img src="https://github.com/carlosavilae/Netflix-Clone/blob/master/img/tv9.PNG?raw=true" alt=""></a>
      <a href=""><img src="https://github.com/carlosavilae/Netflix-Clone/blob/master/img/tv10.PNG?raw=true" alt=""></a>
      <a href=""><img src="https://github.com/carlosavilae/Netflix-Clone/blob/master/img/tv11.PNG?raw=true" alt=""></a>
      <a href=""><img src="https://github.com/carlosavilae/Netflix-Clone/blob/master/img/tv12.PNG?raw=true" alt=""></a>              
    </div>
   
  <!-- END OF MAIN CONTAINER -->
  </section>
</div>

<script src="{% static 'js/forms.js' %}" ></script>

{% endblock %}

src/itens/templates/header_validar_itens.html
<div class="section-header">
    <table style="width: 100%;">
    <tr>
        <td style="width: 30%;">
            <h1 class="header-title"> Itens a Validar </h1>
        </td>
        <td>
            <div class="buttons-validar">
            <table style="width: 100%; text-align: center;">
            <tr>
                <td>
                {% if app_name == 'filme' %}
                    <a class="botao-estilizado-admin" href="{% url 'validar_itens' tipo_item='filme' %}">
                        <i class="fas fa-film"></i>  Filmes
                    </a>
                {% else %}
                    <a class="botao-estilizado" href="{% url 'validar_itens' tipo_item='filme' %}">
                        <i class="fas fa-film"></i>  Filmes
                    </a>
                {% endif %}
                </td>

                <td>
                {% if app_name == 'livro' %}
                    <a class="botao-estilizado-admin" href="{% url 'validar_itens' tipo_item='livro' %}">
                        <i class="fas fa-book"></i>  Livros
                    </a>
                {% else %}
                    <a class="botao-estilizado" href="{% url 'validar_itens' tipo_item='livro' %}">
                        <i class="fas fa-book"></i>  Livros
                    </a>
                {% endif %}
                </td>

                <td>
                {% if app_name == 'serie' %}
                    <a class="botao-estilizado-admin" href="{% url 'validar_itens' tipo_item='serie'%}">
                        <i class="fas fa-theater-masks 2f"></i>  Séries
                    </a>
                {% else %}
                    <a class="botao-estilizado" href="{% url 'validar_itens' tipo_item='serie'%}">
                        <i class="fas fa-theater-masks 2f"></i>  Séries
                    </a>
                {% endif %}
                </td>

            </tr>
            </table>
            </div>
        </td>
    </tr>
    </table>
</div>

src/itens/templates/indicados_p_vc.html
{% load static %}
<h1 id="myList">Indicados para você</h1>
    <div class="box">
      <a href=""><img src="https://github.com/carlosavilae/Netflix-Clone/blob/master/img/t1.PNG?raw=true" alt=""></a>
      <a href=""><img src="https://github.com/carlosavilae/Netflix-Clone/blob/master/img/t2.PNG?raw=true" alt=""></a>
      <a href=""><img src="https://github.com/carlosavilae/Netflix-Clone/blob/master/img/t3.PNG?raw=true" alt=""></a>
      <a href=""><img src="https://github.com/carlosavilae/Netflix-Clone/blob/master/img/t4.PNG?raw=true" alt=""></a>
      <a href=""><img src="https://github.com/carlosavilae/Netflix-Clone/blob/master/img/t5.PNG?raw=true" alt=""></a>
      <a href=""><img src="https://github.com/carlosavilae/Netflix-Clone/blob/master/img/t6.PNG?raw=true" alt=""></a>                  
</div>

src/itens/templates/item.html
{% extends 'base_item.html' %}

{% load static %}

{% load bootstrap4 %}

{% block content %}

<div class="wrapper">
  <section class="main-container" style="background-color: rgb(0, 0, 0);">
      <div class="item-description" style="background-color: rgb(184, 111, 190);">
          <h1 style=" text-transform: capitalize;">{{app_name}}</h1>
          <h1>{{obj.titulo}}</h1>
          <img src= "/media/{{obj.imagem.thumbnail}}"/>
          <br>
          <b>Ano de lançamento - </b> {{obj.ano_lancamento}}
          {% if app_name != 'livro' %}
          <hr>
            <b>Diretor - </b> {{obj.diretor}}
            <hr>
            <b>Elenco - </b> {{obj.elenco}}
            <hr>
            {% if app_name == 'serie' %}
              <b>Número de temporadas - </b> {{serie.qtd_temporadas}}
            <hr> 
            {% endif %}
          
          {% else %}
          <hr>
            <b>Autor - </b> {{obj.autor}}
            <hr>
            <b>Editora - </b> {{obj.editora}}
            <hr>
            <b>Volume - </b> {{obj.volume}}
            <hr>
          {% endif %}

          <b>País - </b> {{obj.pais}}
          <hr>
          <b>Categoria - </b> {{obj.categoria}}
          <br>
          <br>
          <form action="{% url 'avaliar_item' tipo_item=app_name item_id=obj.id%}" method="post" autocomplete="off" enctype="multipart/form-data" class="login100-form validate-form form">
            {% csrf_token %}
              <button type="submit" class="" href="{% url 'avaliar_item' tipo_item=app_name item_id=obj.id %}">
                <h2 style = font-family:Georgia;font-size:18px;>Fazer avaliação</h2>
              </button>
          </form>
      </div>

  </section>
</div>

{% endblock %}

src/itens/templates/validar_itens.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="wrapper">
    <section class="main-container">
        {% include 'header_validar_itens.html' %}

        <br>
        <h2>{{len_objects}} {{obj_name}}{% if len_objects != 1 %}s{% endif %} para validar</h2>

        <div class="itens-box">
            
            {% if status_message %}
            <div class="message-status">
                {{status_message}}
            </div>
            {% endif %}

            {% for item in objects %}

            {% include 'validar_item_box.html' %}

            {% endfor %}

        </div>

    </section>
</div>
{% endblock %}