src/Projeto/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

# importando views da aplicação core
from core.views import IndexView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('conta/', include('django.contrib.auth.urls')),
    path('', include('core.urls')),
    path('amigos/', include('amigos.urls')),
    path('itens/', include('itens.urls')),
    path('avaliacoes/', include('avaliacoes.urls')),
    path('comentario/', include('comentarios.urls'))

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = 'Critic Hub'
admin.site.site_header = 'Admin Critic Hub'
admin.site.index_title = 'Administração Critic Hub'

src/core/urls.py
from django.urls import path

# from .views import cadastro, index, v404, v500, carregar_cidades
from .views import *

urlpatterns = [
    path('', index, name='index'),
    path('cadastro', cadastro, name='cadastro'),
    path('404', v404, name='v404'),
    path('500', v500, name='v500'),

    path('minha_conta', minha_conta, name='minha_conta'),
    path('usuario/<int:pk>', user_view, name='usuario'),
    path('excluir_conta/<int:user_id>', excluir_conta, name='excluir_conta'),

    path('busca/<str:app_name>', searchbar, name='searchbar'),

    path('ajax/get-cidades-ajax/', carregar_cidades, name='get-cidades-ajax'),
]

src/core/models.py
from django.db import models

from django.contrib.auth.models import AbstractUser, BaseUserManager
from stdimage.models import StdImageField

from pyUFbr.baseuf import ufbr

class Estado(models.Model):
    sigla = models.CharField("Sigla", max_length=2)

    def __str__(self):
        return self.sigla
class Cidade(models.Model):
    estado = models.ForeignKey(Estado, on_delete=models.CASCADE, verbose_name="Estado")
    nome = models.CharField("Nome", max_length=60)

    def __str__(self):
        return self.nome

def choice_cidades():
    lista_cidades = []
    for es in ufbr.list_uf:
        cont = 0
        for cidade in ufbr.list_cidades(es):
            tupla_cidade = (es+str(cont), cidade)
            lista_cidades.append(tupla_cidade)
            cont += 1
    return lista_cidades

def choice_estados():
    estados = []
    for estado in ufbr.list_uf:
        estados.append((estado, estado))
    return estados

class UsuarioManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, username, email, first_name, last_name, password=None, **extra_fields):
        if not email:
            raise ValueError('O campo email é obrigatório')
        email = self.normalize_email(email)
        user = self.model(email=email, username=username, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user
    
    def create_user(self, username, email, first_name, last_name, password=None, **extra_fields):
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(username, email, first_name, last_name, password, **extra_fields)
    

    def create_superuser(self, username, email, first_name, last_name, password=None, **extra_fields):
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_staff', True)
        return self._create_user(username, email, first_name, last_name, password, **extra_fields)


class Usuario(AbstractUser):
    # new_user = Usuario(username='teste', email='teste@teste.com', first_name='teste', last_name='teste', password='Teste@123')
    
    # PK = username
    # os campos: username, password, first_name, last_name vem de AbstractUser
    email = models.EmailField('E-mail', unique=True)
    imagem = StdImageField('Imagem Perfil', null=True, blank=True, upload_to='usuarios', variations={'thumbnail':(300,300)})

    estado = models.ForeignKey(Estado, on_delete=models.SET_NULL, verbose_name="Estado", null=True)
    cidade = models.ForeignKey(Cidade, on_delete=models.SET_NULL, verbose_name="Cidade", null=True)

    data_nascimento = models.DateField("Data de Nascimento", null=True)

    amigos = models.ManyToManyField("self", db_table="Amigos", blank=True)

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email', 'first_name', 'last_name']

    objects = UsuarioManager()

    def __str__(self):
        return self.username

    def enviar_pedido_amizade(self, destinatario_id):
        amigo_obj = Usuario.objects.get(pk=destinatario_id)
        meus_pedidos = self.remetente.all()
        if amigo_obj not in meus_pedidos.filter(destinatario=amigo_obj):
            pedido_amizade = PedidosAmizade(remetente=self, destinatario=amigo_obj)
            pedido_amizade.save()
    
    def remover_amigo(self, amigo_id):
        amigo_obj = Usuario.objects.get(pk=amigo_id)
        self.amigos.remove(amigo_obj)
    
    def get_amigos_comum(self, user):
        amigos = [amigo for amigo in self.amigos.all() if amigo in user.amigos.all()]
        num_amigos = len(amigos)
        return num_amigos
    
    def atualizar_registro(self, values):
        for field in values.keys():
            if field == 'username':
                if values[field] != self.username:
                    self.username = values[field] 
            elif field == 'email':
                if values[field] != self.email:
                    self.email = values[field] 
            elif field == 'first_name':
                if values[field] != self.first_name:
                    self.first_name = values[field] 
            elif field == 'last_name':
                if values[field] != self.last_name:
                    self.last_name = values[field] 
            elif field == 'cidade':
                if values[field] != self.cidade:
                    self.cidade = Cidade.objects.get(pk=int(values[field]))
            elif field == 'estado':
                if values[field] != self.estado:
                    self.estado = Estado.objects.get(pk=int(values[field]))
            elif field == 'data_nascimento':
                if values[field] != self.data_nascimento:
                    self.data_nascimento = values[field]

        self.save()




class PedidosAmizade(models.Model):
    create_date = models.DateField(auto_now=True)
    remetente = models.ForeignKey(Usuario, on_delete=models.CASCADE, related_name='remetente')
    destinatario = models.ForeignKey(Usuario, on_delete=models.CASCADE, related_name='destinatario')
    aceito = models.BooleanField('Aceito', default=False)

    def __str__(self):
        return f'{self.remetente} -> {self.destinatario}'

    def aceitar_pedido(self):
        self.remetente.amigos.add(self.destinatario)
        self.aceito = True
        self.save()
    
    def recusar_pedido(self):
        self.delete()

src/core/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.urls import reverse_lazy

from django.views.generic import TemplateView, CreateView

from django.contrib.auth import login, authenticate, logout as auth_logout

from .forms import UsuarioCreateForm, SetPasswordForm

from .models import Cidade, Estado, Usuario
from itens.models import Filme, Livro, Serie
from avaliacoes.models import AvaliacaoFilme, AvaliacaoLivro, AvaliacaoSerie

from django.db.models import Q
from django.contrib import messages
from pyUFbr.baseuf import ufbr
import json
from .backend import adicionar_cidades, filter_cidades, bloquear_acesso, bloquear_acesso_admin
from .backend import obtendo_objetos, obtendo_parametros_busca, filtrando_objetos


## Class Based View
class IndexView(TemplateView):
    template_name = 'index.html'

## Function Based View
@bloquear_acesso
def index(request):
    #import pdb; pdb.set_trace()
    context = {}
    
    filmes = Filme.objects.filter(ativo=True)
    series = Serie.objects.filter(ativo=True)
    livros = Livro.objects.filter(ativo=True)
    
    usuario = request.user
    print(usuario)
    
    # Botões Submit
    if request.method == 'POST':
        if 'adicionar_cidades' in request.POST:
            adicionar_cidades()
            print("Cidades adicionadas")
            return redirect('/')
        elif 'view_cadastro' in request.POST:
            return redirect('/cadastro')
        elif 'do_logout' in request.POST:
            return redirect('/conta/logout')
    objs_add_recentemente= filmes.union(series)
    objs_add_recentemente= objs_add_recentemente.union(livros).order_by('-data_criacao')
    
    cont=0
    objs_add_recentemente_list= []

    for obj in objs_add_recentemente:
        if cont<=6:
            objs_add_recentemente_list.append(obj)
            cont+=1    

    context.update({
        'filmes': filmes,
        'series': series,
        'livros': livros,
        'objs_add_recentemente': objs_add_recentemente_list 
    })

    return render(request, 'index.html', context)


def cadastro(request):
    print(request.user)
    if str(request.method) == 'POST':
        form = UsuarioCreateForm(request.POST, request.FILES)
        print(form.as_p())
        # Validando formulário
        if form.is_valid():
            form.save()
            messages.success(request, " Cadastro realizado com sucesso !")
            # Redirecionando para index após o cadastro
            return redirect('/conta/login')
        else:
            error_fields = "Campos com erro: "
            for erro in form.errors:
                error_fields += erro + ', '
    else:
        form = UsuarioCreateForm()

    context = {
        'form': form,
    }

    return render(request, 'cadastro.html', context)


def carregar_cidades(request):
    estado_id = request.GET.get('estado')
    estado = Estado.objects.get(pk=estado_id)
    cidades = Cidade.objects.all()
    while estado == None:
        estado = request.GET.get('estado')
    print(f"Estado ID = {estado}")
    cidades = filter_cidades(estado)
    
    return render(request, 'hr/city_dropdown_list_options.html', {'cidades', cidades})

def v404(request):
    return render(request, '404.html')


def v500(request):
    return render(request, '500.html')


@bloquear_acesso
def searchbar(request, app_name):
    context = {}
    objs_to_show = []
    itens_apps = ('filme', 'serie', 'livro')
    context['app_name'] = app_name

    context['itens_apps'] = itens_apps

    users = Usuario.objects.all()
    app_name = request.GET.get('select_app', 'usuarios')
    objs = obtendo_objetos(app_name)

    if request.method == 'GET':
        if app_name == 'amigos':
            objs = request.user.amigos.all()
        search_params = obtendo_parametros_busca(app_name)

        # import pdb; pdb.set_trace()

        # Obtendo valores da busca
        search = request.GET.get('search', False)
        context['search_input'] = search

        filtro_busca = request.GET.get('select_filter', 'titulo')
        context['search_filter'] = filtro_busca

        if search:  # Executando se a barra de busca estiver preenchida
            
            search_url = request.get_full_path() # Obtendo URL da busca
            context['search_url'] = search_url

            # Filtrando objetos
            objs_filtered = filtrando_objetos(app_name, objs, search, filtro_busca)
            
            if app_name in ('usuarios', 'amigos'):
                list_dict = []
                len_amigos = []
                user_amigos = {}
                # Obtendo amigos em comum
                for user in objs_filtered:
                    amigos = user.amigos.all()
                    amigos_em_comum = [amigo for amigo in amigos if amigo in request.user.amigos.all()]
                    list_dict.append({'user': user, 'amigos_comum': amigos_em_comum, 'cont': len(amigos_em_comum)})
                    user_amigos.update({user: amigos_em_comum})
                # Ordenando por mais amigos em comum
                list_dict = sorted(list_dict, key=lambda k: k['cont'])
                # Mapeando amigos em comum com usuario
                for item in list_dict:
                    objs_to_show.append(item['user'])
                    len_amigos.append(item['user'].get_amigos_comum(request.user))
                
                usuarios_solicitados = []
                for pedido in request.user.remetente.filter(aceito=False):
                    usuarios_solicitados.append(pedido.destinatario)

                context.update({
                    'usuarios': objs_to_show, # -> List
                    'user_amigos': user_amigos, # -> Dict
                    'len_amigos': len_amigos,
                    'usuarios_solicitados': usuarios_solicitados,
                })

            elif app_name in itens_apps:
                for item in objs_filtered:
                    objs_to_show.append(item)
                context.update({
                    'itens': objs_to_show, # -> List
                    'search_filters': search_params,
                })

        else: # Executando se a barra de busca não estiver preenchida
            if app_name in itens_apps:
                if app_name == 'filme':
                    context['filmes'] = objs
                elif app_name == 'livro':
                    context['livros'] = objs
                elif app_name == 'serie':
                    context['filmes'] = objs
                context['search_filters'] = search_params
                return redirect(f'/itens/{app_name}')

    # Atualizando contexto
    context.update({
        'objs': objs_to_show,
        'len_resultados': len(objs_to_show), # -> Int
        'searching': True,
    })
    return render(request, 'busca/base_busca.html', context)

@bloquear_acesso
def minha_conta(request):
    context = {}
    user = request.user
    av_filmes = user.avaliacaofilme_set.all()
    av_livros = user.avaliacaolivro_set.all()
    av_series = user.avaliacaoserie_set.all()

    avaliacoes = av_filmes.union(av_livros)
    avaliacoes = avaliacoes.union(av_series)
    avaliacoes = avaliacoes.order_by('create_date')

    estados = Estado.objects.all().order_by('id')
    cidades = Cidade.objects.all().order_by('id')

    # import pdb; pdb.set_trace()

    form_alterar_senha = SetPasswordForm(user)

    if request.method == 'POST':
        if 'editar_perfil' in request.POST:
            user.atualizar_registro(request.POST)
            status_message = "Dados Atualizados !"
            context['status_message'] = status_message
        elif 'alterar_senha' in request.POST:
            form_alterar_senha = SetPasswordForm(user, request.POST)
            if form_alterar_senha.is_valid():
                form_alterar_senha.save()
                status_message = "Senha Alterada com sucesso !"
                context['status_message'] = status_message
    
    context.update({
        'user': user,
        'avaliacoes':avaliacoes,
        'estados': estados,
        'cidades': cidades,
        'form_alterar_senha': form_alterar_senha,
    })
    return render(request, 'minha_conta.html', context)

@bloquear_acesso
def user_view(request, pk):
    context = {}  
    user = Usuario.objects.get(pk=pk)
    if request.method == 'POST':
        #import pdb; pdb.set_trace()   
        if 'excluir_usuario' in request.POST:
            request.user.remover_amigo(pk)     
        
        elif 'adicionar_usuario' in request.POST:
            request.user.enviar_pedido_amizade(pk)

    amigos = user.amigos.all()
    amigos_em_comum = [amigo for amigo in amigos if amigo in request.user.amigos.all()]

    av_filmes = user.avaliacaofilme_set.all()
    av_livros = user.avaliacaolivro_set.all()
    av_series = user.avaliacaoserie_set.all()

    avaliacoes = av_filmes.union(av_livros)
    avaliacoes = avaliacoes.union(av_series)
    avaliacoes = avaliacoes.order_by('create_date')
   
    usuarios_solicitados = []
    for pedido in request.user.remetente.filter(aceito=False):
        usuarios_solicitados.append(pedido.destinatario)
    
    context.update({
        'usuario': user,
        'amigos': amigos,
        'amigos_em_comum': amigos_em_comum,
        'len_amigos_comum':len(amigos_em_comum),
        'avaliacoes': avaliacoes,
        'filme_av_class': AvaliacaoFilme,
        'livro_av_class': AvaliacaoLivro,
        'serie_av_class': AvaliacaoSerie,
        'usuarios_solicitados': usuarios_solicitados
    })

    return render(request, 'usuario.html', context)

def excluir_conta(request, user_id):
    context = {}

    user = request.user

    if request.method == 'POST':
        if 'confirmar' in request.POST:
            auth_logout(request)
            user.delete()
            return redirect('/conta/login')
        elif 'voltar' in request.POST:
            return redirect('/minha_conta')

    return render(request, 'excluir_conta.html', context)

src/core/templates/base_header_section.html
{% load static %}
{% load bootstrap4 %}
<!-- Header de Sections com barra de busca -->
<div class="section-header">
    <table style="width: 100%;">
        <tr>
            <!-- Coluna - Titulo da Página -->
            {% if searching %}
            <td style="width: 55%;">
            {% else %}
            <td style="width: 30%;">
            {% endif %}

            {% if searching and app_name != 'amigos' %}
            <h1 class="header-title">
                Resultados da busca para " {{ search_input }} "
            </h1>
            {% else %}
            <h1 class="header-title">
                {% if app_name == 'filme' %}
                        Filmes

                {% elif app_name == 'livro' %}
                        Livros

                {% elif app_name == 'serie' %}
                        Séries

                {% elif app_name == 'amigos' %}
                    {% if app_pedidos %}
                        Pedidos de Amizade
                    {% else %}
                        Seus Amigos
                    {% endif %}

                {% elif app_name == 'usuarios' %}
                        Usuários
                {% endif %}
                </h1>
            {% endif %}

            </td>
            <!-- Coluna - Barra de Busca -->
            {% if searching %}
            <td style="width: 30%; padding-right: 30px;">
            {% else %}
            <td style="width: 40%; padding-right: 30px;">
            {% endif %}
                <!-- Incluindo barra de busca -->
                {% include 'busca/barra_busca.html' %}
            </td>
            <!-- Coluna - Direita com infos da busca -->
            {% if searching %}
            <td style="width: 10%;">
            {% else %}
            <td style="width: 20%;">
            {% endif %}
                <p style="padding-left: 15px; margin-right: 20px; float: right;">
                {% if app_name != 'amigos' %}
                    {{len_resultados}} Resultado{% if len_resultados != 1 %}s{% endif %} de {{app_name}}
                {% else %}
                    {% if app_pedidos %}

                    {{len_resultados}} Pedido{% if len_resultados != 1 %}s{% endif %} de Amizade
                    {% else %}
                    {{len_resultados}} Amigo{% if len_resultados != 1 %}s{% endif %}
                
                    {% endif %}
                {% endif %}
                </p>
            </td>
        </tr>
    </table>

    <!-- BOX DOS BOTÕES -->
    <hr style="margin:0px;"/>
    <div class="sub-section-header">
        <form action="">
            <div class="buttons-box" style="text-align: right;float: right;">
                <!-- Primeiro Botão -->
                {% if app_name == 'amigos' %}
                    <a class="botao-estilizado" href="{% url 'add_amigos' %}"><i class="fas fa-location-arrow"></i>  Encontrar Amigos</a>
                {% elif app_name == 'usuarios' %}
                    <a class="botao-estilizado" href="{% url 'seus_amigos' %}"><i class="fas fa-user-friends"></i>  Seus Amigos</a>
                
                {% else %}
                    {% if user.is_superuser %}
                    <a class="botao-estilizado-admin" href="{% url 'validar_itens' tipo_item=app_name %}"><i class="fas fa-check-double"></i>  Validar Cadastros</a>
                    {% endif %}
                {% endif %}
                <!-- Segundo Botão -->
                {% if app_name == 'amigos' or app_name == 'usuarios' %}
                    {% if app_pedidos %}
                        <a class="botao-estilizado" href="{% url 'seus_amigos' %}"><i class="fas fa-user-friends"></i>  Seus Amigos</a>
                    {% else %}
                        <a class="botao-estilizado" href="{% url 'pedidos_amizade' %}"><i class="fas fa-user-plus"></i>  Pedidos de Amizade</a>
                    {% endif %}

                {% else %}
                    <a class="botao-estilizado" href="{% url 'cadastro_item' app_name=app_name %}" >
                        <i class="fas fa-plus"></i>  Cadastrar
                        {% if app_name == 'filme' %} Filme
                        {% elif app_name == 'livro' %} Livro
                        {% elif app_name == 'serie' %} Série
                        {% endif %}
                    </a>
                {% endif %}
            </div>
        </form>
    </div>

</div>

src/core/templates/cadastro.html
{% extends 'base_login.html' %}
{% load static %}
{% load bootstrap4 %}

{% block title %}Cadastro{% endblock %}
{% block content %}
<div class="limiter" style="background-image: url({% static 'images/fundo.png' %})" >
	<div class="container-login100">
		<div class="wrap-login100">
			
			<span class="login100-form-title">
				<img src="{% static 'images/logo_critichub2.png' %}" alt="Logo" width="350" height="140">
			</span>

			<form method="post" autocomplete="off" 
				enctype="multipart/form-data" class="login100-form validate-form form"
				id="cadastroForm" data-cities-data="{% url 'get-cidades-ajax' %}">

			{% csrf_token %}
			{{ form.media.js }}

			<h1 style="text-align: center; color:white">Cadastro</h1>

			{% bootstrap_messages %}

			{% bootstrap_form form %}
			
			<div class="container-login100-form-btn">
			{% buttons %}
				<button type="submit" class="login100-form-btn btn btn-secondary">
					<h2 style = color:black;font-size:14px;>Criar Conta</h2>
				</button>
				<button type="submit" class="btn" 
						style="display:flex; margin-top: 10px; margin-left: 25%;">
					<a href="{% url 'login' %}" style = color:black;font-size:14px;>Voltar</a>
				</button>
			{% endbuttons %}
			</div>

		 </form>
		</div>
	</div>
</div>
<div id="dropDownSelect1"></div>

{% bootstrap_javascript jquery='full' %}


<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script type='text/javascript'>
	$('#id_estado').change(function(){
		var url = $("#cadastroForm").attr("data-cities-url");
		var estado_id = $('#id_estado').val();

		$.ajax({
			url: url,
			type: 'GET',
			data:{
				'estado': estado_id
			},
			success: function(data){
				console.log("TESTE -------------------");
				console.log(data);
				$('#id_cidade').html("<option value=\"\">TESTE</option>");
			}
		});
		//$('select[name=cidade]').load("{% url 'get-cidades-ajax' %}");
	});
</script>

{% endblock %}

src/core/templates/excluir_conta.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="wrapper">
    <section class="main-container">
        <h1 style="padding-top: 70px;">Atenção, você clicou no botão de EXCLUIR CONTA deseja mesmo proseguir?</h1>
        <h3>Após a confirmação a operação não poderá ser revertida.</h3>

        <form action="{% url 'excluir_conta' user_id=user.id %}" method="post">
            {% csrf_token %}
            <input name="confirmar" type="submit" class="botao-avaliacao validar-excluir" style="float: none;" value="Excluir Conta"/>
            <input name="voltar" type="submit" class="botao-avaliacao validar-aprovar" style="float: none;" value="Voltar"/>
        </form>
    </section>
</div>
{% endblock %}

src/core/templates/form_editar_conta.html
{% load static %}
    <form action="{% url 'minha_conta' %}" method="post" style="padding-bottom: 30px;">
      {% csrf_token %}
      <fieldset >
        <div>
            <label for="username">Nome de Usuário:</label>
            <input type="text" id="id_username" name="username" size="40" value="{{user.username}}"/>
        </div><br>
        <div>
            <label for="email">E-mail:</label>
            <input type="email" id="id_email" name="email" size="40" value="{{user.email}}"/>
        </div><br>
        <div>
            <label for="first_name">Primeiro Nome:</label>
            <input type="text" id="id_first_name" name="first_name" size="40" value="{{user.first_name}}"/>
        </div><br>
        <div>
            <label for="last_name">Ultimo Nome:</label>
            <input type="text" id="id_last_name" name="last_name" size="40" value="{{user.last_name}}"/>
        </div><br>
        <div>
          <label for="cidade">Cidade:</label>
            <select id="id_cidade" name="cidade">
              {% for cidade in cidades %}
                {% if cidade.id != user.cidade.id %}
                <option value={{cidade.id}}>{{cidade.nome}}</option>
                {% else %}
                <option value={{cidade.id}} selected>{{cidade.sigla}}</option>
                {% endif %}
              {% endfor %}
              </select>
        </div><br>
        <div>
            <label for="nome">Estado:</label>
            <select id="id_estado" name="estado">
            {% for estado in estados %}
              {% if estado.id != user.estado.id %}
              <option value={{estado.id}}>{{estado.sigla}}</option>
              {% else %}
              <option value={{estado.id}} selected>{{estado.sigla}}</option>
              {% endif %}
            {% endfor %}
            </select>
        </div><br>
        <div>
            <label for="data_nascimento">Data de nascimento:</label>
            <input type="date" id="id_data_nascimento" name="data_nascimento" required value="{{user.data_nascimento}}"/>
        </div><br>
        <div style="text-align: center;">
          <input name="editar_perfil" class="botao-avaliacao comentario" style="float: none;" type="submit">
        </div>
    </fieldset>
    </form>

src/core/templates/usuario.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="wrapper">
    <section class="main-container" >
      <h2 align="center" style="padding-top: 80px;">Usuário</h2>
      <table style="width: 100%; margin-top: 50px;">
        <tr>
          <td style="width: 310px;">
            <div class="fotoperfil">
              {% if usuario.imagem %}
              {{usuario.imagem}}
              {% else %}
              <img src="{% static 'images/semfoto.jpeg' %}" alt="Imagem" style="width: 300px;">
              {% endif %}
            </div>
          </td>
          <td style="vertical-align: top; padding-left: 50px;">
            <div style="padding: 0px;">
              <h2>Nome de usuário: <span style="color: white;">{{usuario.username}}</span></h2>
              <h2>Número de Amigos: <span style="color: white;">{{usuario.amigos.all.count}}</span></h2>
              <h2>Número de Amigos em comum: <span style="color: white;">{{len_amigos_comum}}</span></h2>
              <h2>Número de Avaliações: <span style="color: white;">{{usuario.amigos.all.count}}</span></h2>
            </div>
          </td>
      </tr>
      </table>
      <div>
        <form action="{% url 'usuario' pk=usuario.pk %}" method="POST">
          {% csrf_token %}
          {% if usuario in user.amigos.all %}
            <button class="botao-validar validar-excluir" type="submit" name="excluir_usuario">Excluir Usuário</button>
            <span style="padding-right: 80px;"></span>
            
            {% elif usuario in usuarios_solicitados %}            
            <i id="icon-added" class="fas fa-check"> Solicitação enviada</i>
          
            {% else %}
            <button class="botao-validar validar-aprovar" type="submit" name="adicionar_usuario">Adicionar Usuário</button>
          {%endif%}
        </form>
      </div>

      <div class="section-header" style="background-color: rgb(111, 48, 194);width: 95%;margin: auto; margin-top: 60px;">
        <h1 class="header-title" style="padding-top: 10px;">
            Avaliações do usuário
        </h1>
      </div>
      
      {% for avaliacao in avaliacoes %}
      {% include 'avaliacoes.html' %}
      {% endfor %}
    </section>
</div>
{% endblock %}