src/Projeto/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

# importando views da aplicação core
from core.views import IndexView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('conta/', include('django.contrib.auth.urls')),
    path('', include('core.urls')),
    path('amigos/', include('amigos.urls')),
    path('itens/', include('itens.urls')),
    path('avaliacoes/', include('avaliacoes.urls')),
    path('comentario/', include('comentarios.urls'))

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

admin.site.site_header = 'Critic Hub'
admin.site.site_header = 'Admin Critic Hub'
admin.site.index_title = 'Administração Critic Hub'

src/avaliacoes/urls.py
from django.urls import path

from .views import *

urlpatterns = [
    path('avaliar/<str:tipo_item>/<int:item_id>', avaliar_item, name='avaliar_item'),
    path('usuario/<int:user_id>/', avaliacoes_usuario, name='avaliacoes_usuario'),
    path('<str:tipo_item>/<int:item_id>/', avaliacoes_item, name='avaliacoes_item'),
    path('<str:tipo_item>/<int:item_id>/<int:av_id>', avaliacao, name='avaliacao'),
]

src/core/urls.py
from django.urls import path

# from .views import cadastro, index, v404, v500, carregar_cidades
from .views import *

urlpatterns = [
    path('', index, name='index'),
    path('cadastro', cadastro, name='cadastro'),
    path('404', v404, name='v404'),
    path('500', v500, name='v500'),

    path('minha_conta', minha_conta, name='minha_conta'),
    path('usuario/<int:pk>', user_view, name='usuario'),
    path('excluir_conta/<int:user_id>', excluir_conta, name='excluir_conta'),

    path('busca/<str:app_name>', searchbar, name='searchbar'),

    path('ajax/get-cidades-ajax/', carregar_cidades, name='get-cidades-ajax'),
]

src/avaliacoes/models.py
from django.db import models

from core.models import Usuario
from itens.models import Filme, Livro, Serie


class Avaliacao(models.Model):
    VALOR_CHOICES = (
        (0, 0),
        (1, 1),
        (2, 2),
        (3, 3),
        (4, 4),
        (5, 5),
        (6, 6),
        (7, 7),
        (8, 8),
        (9, 9),
        (10, 10)
    )

    create_date = models.DateTimeField("Data de Criação", auto_now=True, blank=True)
    user_id = models.ForeignKey(Usuario, on_delete=models.CASCADE, verbose_name="user_id", blank=True)
    valor = models.IntegerField("Avaliação", choices=VALOR_CHOICES)
    avaliacao = models.CharField("Comentário", max_length=200, null=True)

    class Meta:
        verbose_name = "Avaliação"
        verbose_name_plural = "Avaliações"
        abstract = True
    
    def get_class(self):
        return self.__class__

class AvaliacaoFilme(Avaliacao):
    item = models.ForeignKey(Filme, on_delete=models.CASCADE, blank=True)

    def curtir(self, user_id):
        like = LikeAvaliacaoFilme(user_id=user_id, avaliacao=self)
        like.save()

    def descurtir(self, user_id):
        like = LikeAvaliacaoFilme.objects.get(user_id=user_id)
        like.delete()

class AvaliacaoLivro(Avaliacao):
    item = models.ForeignKey(Livro, on_delete=models.CASCADE, blank=True)
    
    def curtir(self, user_id):
        like = LikeAvaliacaoLivro(user_id=user_id, avaliacao=self)
        like.save()

    def descurtir(self, user_id):
        like = LikeAvaliacaoLivro.objects.get(user_id=user_id)
        like.delete()

class AvaliacaoSerie(Avaliacao):
    item = models.ForeignKey(Serie, on_delete=models.CASCADE, blank=True)

    def curtir(self, user_id):
        like = LikeAvaliacaoSerie(user_id=user_id, avaliacao=self)
        like.save()
    
    def descurtir(self, user_id):
        like = LikeAvaliacaoSerie.objects.get(user_id=user_id)
        like.delete()

class LikeAv(models.Model):
    user_id = models.ForeignKey(Usuario, on_delete=models.CASCADE, verbose_name="user_id", blank=True)
    class Meta:
        abstract = True
        verbose_name = 'Like'
        verbose_name_plural = 'Likes'

class LikeAvaliacaoFilme(LikeAv):
    avaliacao = models.ForeignKey(AvaliacaoFilme, on_delete=models.CASCADE)

class LikeAvaliacaoLivro(LikeAv):
    avaliacao = models.ForeignKey(AvaliacaoLivro, on_delete=models.CASCADE)

class LikeAvaliacaoSerie(LikeAv):
    avaliacao = models.ForeignKey(AvaliacaoSerie, on_delete=models.CASCADE)

src/avaliacoes/forms.py
from django import forms

from .models import AvaliacaoFilme, AvaliacaoSerie, AvaliacaoLivro
    
class AvaliarFilme(forms.ModelForm):
    class Meta:
        model = AvaliacaoFilme
        fields = ['avaliacao', 'valor', 'item', 'user_id']
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.keys():
            self.fields[field].required = True
            self.fields[field].help_text = '' 
               

class AvaliarSerie(forms.ModelForm):
    class Meta:
        model = AvaliacaoSerie
        fields = ['avaliacao', 'valor', 'item', 'user_id']
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.keys():
            self.fields[field].required = True
            self.fields[field].help_text = '' 

class AvaliarLivro(forms.ModelForm):
    class Meta:
        model = AvaliacaoLivro
        fields = ['avaliacao', 'valor', 'item', 'user_id']
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.keys():
            self.fields[field].required = True
            self.fields[field].help_text = '' 

src/avaliacoes/views.py
from django.shortcuts import render, redirect

from itens.views import item
from .forms import  AvaliarFilme, AvaliarSerie, AvaliarLivro

from .models import *
from itens.models import *
from comentarios.models import *


def avaliar_item(request, tipo_item, item_id):
    #import pdb; pdb.set_trace()    
    context = {}
    context['app_name'] = tipo_item

    if tipo_item == 'filme':
        obj_class = Filme
        form = AvaliarFilme()
        obj_name = 'Filme'
    elif tipo_item == 'livro':
        obj_class = Livro
        form = AvaliarLivro()
        obj_name = 'Livro'
    elif tipo_item == 'serie':
        obj_class = Serie
        form = AvaliarSerie()
        obj_name = 'Série'
   
    obj = obj_class.objects.get(pk=item_id)
    context['obj_name'] = obj_name
    context['obj'] = obj

    if request.method == 'POST':
        if tipo_item == 'filme':
            form = AvaliarFilme(request.POST, request.FILES)
        elif tipo_item == 'livro':
            form = AvaliarLivro(request.POST, request.FILES)
        elif tipo_item == 'serie':
            form = AvaliarSerie(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            status_message="Avaliação efetuada!"
            context['status_message'] = status_message
            request.session['status_message']= status_message
            return redirect(f"/itens/{tipo_item}/{item_id}")    

    context['form'] = form

    return render(request, 'avaliar_item.html', context)


def avaliacao(request, tipo_item, item_id, av_id):
    context = {}
    context['app_name'] = tipo_item
    context['url_avaliacao'] = request.get_full_path()

    if tipo_item == 'filme':
        obj_class = AvaliacaoFilme
        item_class = Filme
        comentario_class = ComentarioFilme
        obj_name = 'Filme'
        plural_obj_name = 'Filmes'
        search_params = ('titulo', 'pais', 'diretor')

    elif tipo_item == 'livro':
        obj_class = AvaliacaoLivro
        item_class = Livro
        comentario_class = ComentarioLivro
        obj_name = 'Livro'
        plural_obj_name = 'Livros'
        search_params = ('titulo', 'pais', 'autor')

    elif tipo_item == 'serie':
        obj_class = AvaliacaoSerie
        item_class = Serie
        comentario_class = ComentarioSerie
        obj_name = 'Série'
        plural_obj_name = 'Séries'
        search_params = ('titulo', 'pais', 'diretor')

    obj = obj_class.objects.get(pk=av_id)
    item_obj = item_class.objects.get(pk=item_id)

    if request.method == 'POST':
        if 'form_avaliacao' in request.POST:
            if 'curtir' in request.POST:
                obj.curtir(request.user)
            elif 'descurtir' in request.POST:
                obj.descurtir(request.user)
            elif 'comentar_action' in request.POST:
                texto_comentario = request.POST.get('comentario_field', False)
                if texto_comentario:
                    new_comentario = comentario_class(user_id=request.user, texto=texto_comentario, avaliacao=obj)
                    new_comentario.save()
                    context['new_comentario'] = new_comentario

        elif 'form_comentario' in request.POST:
            comentario = comentario_class.objects.get(pk=int(request.POST.get('comentario_id')))
            if tipo_item == 'filme':
                likes_comentario = comentario.likecomentariofilme_set.all()
            elif tipo_item == 'livro':
                likes_comentario = comentario.likecomentariolivro_set.all()
            elif tipo_item == 'serie':
                likes_comentario = comentario.likecomentarioserie_set.all()

            comentario_liked_users = []
            for like in likes_comentario:
                comentario_liked_users.append(like.user_id)

            if 'curtir' in request.POST:
                if request.user not in comentario_liked_users:
                    comentario.curtir(request.user)
                else:
                    comentario.descurtir(request.user)
            elif 'descurtir' in request.POST:
                comentario.descurtir(request.user)

    if tipo_item == 'filme':
        likes = obj.likeavaliacaofilme_set.all()
        comentarios = obj.comentariofilme_set.filter(comentario_pai=None)
    elif tipo_item == 'livro':
        likes = obj.likeavaliacaolivro_set.all()
        comentarios = obj.comentariolivro_set.filter(comentario_pai=None)
    elif tipo_item == 'serie':
        likes = obj.likeavaliacaoserie_set.all()
        comentarios = obj.comentarioserie_set.filter(comentario_pai=None)

    liked_users = []
    for like in likes:
        liked_users.append(like.user_id)

    context.update({
        'obj': obj,
        'item_obj': item_obj,
        'obj_name': obj_name,
        'plural_obj_name': plural_obj_name,
        'search_filters': search_params,
        'liked_users': liked_users,
        'comentarios': comentarios,
    })

    return render(request, 'avaliacao.html', context)

def avaliacoes_item(request, tipo_item, item_id):
    context = {}
    context['app_name'] = tipo_item

    if tipo_item == 'filme':
        # Classes
        av_class = AvaliacaoFilme
        item_class = Filme
        comentario_class = ComentarioFilme
        # Strings
        obj_name = 'Filme'
        plural_obj_name = 'Filmes'
        search_params = ('titulo', 'pais', 'diretor')
        # Objects
        item_obj = item_class.objects.get(pk=item_id)
        avaliacoes = item_obj.avaliacaofilme_set.all().order_by('create_date')

    elif tipo_item == 'livro':
        # Classes
        av_class = AvaliacaoLivro
        item_class = Livro
        comentario_class = ComentarioLivro
        # Strings
        obj_name = 'Livro'
        plural_obj_name = 'Livros'
        search_params = ('titulo', 'pais', 'autor')
        # Objects
        item_obj = item_class.objects.get(pk=item_id)
        avaliacoes = item_obj.avaliacaolivro_set.all().order_by('create_date')

    elif tipo_item == 'serie':
        # Classes
        av_class = AvaliacaoSerie
        item_class = Serie
        comentario_class = ComentarioSerie
        # Strings
        obj_name = 'Série'
        plural_obj_name = 'Séries'
        search_params = ('titulo', 'pais', 'diretor')
        # Objects
        item_obj = item_class.objects.get(pk=item_id)
        avaliacoes = item_obj.avaliacaoserie_set.all().order_by('create_date')

    """if request.method == 'POST':
        if 'curtir' in request.POST:
            obj.curtir(request.user)
        elif 'descurtir' in request.POST:
            obj.descurtir(request.user)
        elif 'comentar_action' in request.POST:
            texto_comentario = request.POST.get('comentario_field', False)
            if texto_comentario:
                new_comentario = comentario_class(user_id=request.user, texto=texto_comentario, avaliacao=obj)
                new_comentario.save()
                context['new_comentario'] = new_comentario"""

    context.update({
        'item_obj': item_obj,
        'obj_name': obj_name,
        'plural_obj_name': plural_obj_name,
        'search_filters': search_params,
    })

    return render(request, 'avaliacoes_item.html', context)

def avaliacoes_usuario(request, user_id):
    context = {}
    usuario = Usuario.objects.get(pk=user_id)
    # import pdb; pdb.set_trace()
    avaliacoes_filmes = usuario.avaliacaofilme_set.all()
    avaliacoes_livros = usuario.avaliacaolivro_set.all()
    avaliacoes_series = usuario.avaliacaoserie_set.all()
    #avaliacoes = avaliacoes.order_by('create_date')

    context.update({
        'usuario': usuario,
        'avaliacoes_filmes': avaliacoes_filmes,
        'avaliacoes_livros': avaliacoes_livros,
        'avaliacoes_series': avaliacoes_series,
    })
    return render(request, 'avaliacoes_usuario.html', context)

src/avaliacoes/templates/avaliacao.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<div class="wrapper">
    <section class="main-container">
        <div class="section-header">
            <h1 class="header-title" style="padding-top: 10px;">
                Avaliação d{% if app_name == 'serie' %}a{% else %}o{% endif %} {{obj_name}} ' {{item_obj.titulo}} '
            </h1>
        </div>

        {% if new_comentario %}
            <div class="message-status">
                Comentário registrado! 
            </div>
        {% endif %}

        <div class="avaliacao-self" style="margin-top: 20px;">
            <table style="width: 100%;">
                <tr>
                    <td class="coluna-validar" style="width: 30%;">
                        <p>
                            <b style="font-size: 24px;">
                                {{obj_name}}: <a style="text-decoration: none; color: rgb(79, 14, 85);" href="{% url 'item' tipo_item=app_name pk=item_obj.pk %}">{{item_obj.titulo}}</a>
                                <br>
                                Nota: {{obj.valor}}
                            <br><br></b>
                        </p>
                    </td>
                    <td class="coluna-validar" colspan="2">
                        <p style="font-size: 20px;"><b>Comentário</b>: {{obj.avaliacao}}</p>
                    </td>
                </tr>
                <tr style="max-height: 50px;">
                    <td>
                        <p>
                            <b>Autor da avaliação</b>: <a href="{% url 'usuario' pk=obj.user_id.id %}">{{obj.user_id.username}}</a>
                        </p>
                    </td>
                    <td>
                        <p>
                            {% if app_name == 'filme' %}
                            <b>Likes:</b> {{obj.likeavaliacaofilme_set.all.count}}
                            {% elif app_name == 'livro' %}
                            <b>Likes:</b> {{obj.likeavaliacaolivro_set.all.count}}
                            {% elif app_name == 'serie' %}
                            <b>Likes:</b> {{obj.likeavaliacaoserie_set.all.count}}
                            {% endif %}
                        </p>
                    </td>

                    <td>
                        <p>
                            {% if app_name == 'filme' %}
                            <b>Comentários</b>: {{obj.comentariofilme_set.all.count}}
                            {% elif app_name == 'livro' %}
                            <b>Comentários</b>: {{obj.comentariolivro_set.all.count}}
                            {% elif app_name == 'serie' %}
                            <b>Comentários</b>: {{obj.comentarioserie_set.all.count}}
                            {% endif %}
                        </p>
                    </td>
                    <td>
                        <form action="{% url 'avaliacao' tipo_item=app_name item_id=item_obj.id av_id=obj.id %}" method="post">
                            {% csrf_token %}
                            <input type="text" name="form_avaliacao" value="true" style="display: none;">
                            <button type="button" id="btn_comentar" name='comentar' class="botao-avaliacao comentario"><i class="fa fa-comment"></i> Comentar</button>
                            {% if user not in liked_users %}
                            <button type="submit" id="curtir" name='curtir' class="botao-avaliacao like"><i class="fa fa-thumbs-up"></i> Like</button>
                            {% else %}
                            <button type="submit" id="descurtir" name='descurtir' class="botao-avaliacao liked"><i class="fa fa-thumbs-down"></i> Descurtir</button>
                            {% endif %}
                        </form>
                    </td>
                </tr>
            </table>
        </div>

        <div id="id_novo_comentario" class="novo-comentario" style="display: none;">
            <form action="{% url 'avaliacao' tipo_item=app_name item_id=item_obj.id av_id=obj.id %}" method="post">
                {% csrf_token %}
                <input type="text" name="form_avaliacao" value="true" style="display: none;">
                <label for="id_comentario_field">Comentário: </label><br>
                <textarea id="id_comentario_field" name='comentario_field' style="width: 80%; height: 50px;"></textarea>
                <button id="btn_comentar" name='comentar_action' class="botao-avaliacao comentario"><i class="fa fa-comment"></i> Comentar</button>
            </form>
        </div>

        <div class="section-header" style="background-color: rgb(111, 48, 194);width: 90%;margin: auto;">
            <h1 class="header-title" style="padding-top: 10px;">
                Comentários dessa Avaliação
            </h1>
        </div>

        {% for comentario in comentarios %}
        <div class="comentarios-avaliacao">
            <table style="width: 100%;">
                <tr>
                    <td>
                        <p style="padding:10px 0px 0px; margin: 0px;">
                        <a href="{% url 'usuario' pk=comentario.user_id.id %}" style="text-decoration: none;">
                            @{{comentario.user_id.username}}</a>: <b>{{comentario.texto}}</b>
                        </p>
                    </td>
                    <td style="float: right;">
                        <p>
                            Likes: 
                            {% if app_name == 'filme' %}
                            <b>{{comentario.likecomentariofilme_set.all.count}}</b>
                            {% elif app_name == 'livro' %}
                            <b>{{comentario.likecomentariolivro_set.all.count}}</b>
                            {% elif app_name == 'serie' %}
                            <b>{{comentario.likecomentarioserie_set.all.count}}</b>
                            {% endif %}
                        </p>
                        <form action="{% url 'avaliacao' tipo_item=app_name item_id=item_obj.id av_id=obj.id %}" method="post">
                            {% csrf_token %}
                            <input type="text" name="form_comentario" value="true" style="display: none;">
                            <input type="text" name="comentario_id" required value="{{comentario.id}}" style="display:none;">
                            <button type="submit" name='curtir' class="botao-avaliacao like"><i class="fa fa-thumbs-up"></i> Like</button>
                        </form>
                        <form action="{% url 'comentar' tipo_item=app_name pk=comentario.id %}" method="post">
                            {% csrf_token %}
                            <input type="text" name="form_comentario" value="true" style="display: none;">
                            <input type="text" name="url_avaliacao" value="{{url_avaliacao}}" style="display: none;">
                            <input type="text" name="comentario_id" required value="{{comentario.id}}" style="display:none;">
                            <button type="submit" name='comentar_comentario' class="botao-avaliacao comentario"><i class="fa fa-comment"></i> Comentar</button>
                        </form>
                    </td>
                </tr>
            </table>
        </div>
        {% if app_name == 'filme' %}
            {% for comentario_filho in comentario.comentariofilme_set.all %}
            <div class="comentarios-avaliacao" style="width: 80%; padding-left: 20px; background-color: rgb(236, 213, 213);">
                <table style="width: 100%; padding-left: 20px;">
                    <tr>
                        <td>
                            <p style="padding:10px 0px 0px; margin: 0px;">
                            <a href="{% url 'usuario' pk=comentario_filho.user_id.id %}" style="text-decoration: none;">
                                @{{comentario_filho.user_id.username}}</a>: <b>{{comentario_filho.texto}}</b>
                            </p>
                        </td>
                        <td style="float: right;">
                            <p>
                                Likes: 
                                {% if app_name == 'filme' %}
                                <b>{{comentario_filho.likecomentariofilme_set.all.count}}</b>
                                {% elif app_name == 'livro' %}
                                <b>{{comentario_filho.likecomentariolivro_set.all.count}}</b>
                                {% elif app_name == 'serie' %}
                                <b>{{comentario_filho.likecomentarioserie_set.all.count}}</b>
                                {% endif %}
                            </p>
                            <form action="{% url 'avaliacao' tipo_item=app_name item_id=item_obj.id av_id=obj.id %}" method="post">
                                {% csrf_token %}
                                <input type="text" name="form_comentario" value="true" style="display: none;">
                                <input type="text" name="comentario_id" required value="{{comentario_filho.id}}" style="display:none;">
                                <button type="submit" name='curtir' class="botao-avaliacao like"><i class="fa fa-thumbs-up"></i> Like</button>
                            </form>
                        </td>
                    </tr>
                </table>
            </div>
            {% endfor %}
        {% elif app_name == 'livro' %}
            {% for comentario_filho in comentario.comentariolivro_set.all %}
            <div class="comentarios-avaliacao" style="width: 80%; padding-left: 20px; background-color: rgb(236, 213, 213);">
                <table style="width: 100%; padding-left: 20px;">
                    <tr>
                        <td>
                            <p style="padding:10px 0px 0px; margin: 0px;">
                            <a href="{% url 'usuario' pk=comentario_filho.user_id.id %}" style="text-decoration: none;">
                                @{{comentario_filho.user_id.username}}</a>: <b>{{comentario_filho.texto}}</b>
                            </p>
                        </td>
                        <td style="float: right;">
                            <p>
                                Likes: 
                                {% if app_name == 'filme' %}
                                <b>{{comentario_filho.likecomentariofilme_set.all.count}}</b>
                                {% elif app_name == 'livro' %}
                                <b>{{comentario_filho.likecomentariolivro_set.all.count}}</b>
                                {% elif app_name == 'serie' %}
                                <b>{{comentario_filho.likecomentarioserie_set.all.count}}</b>
                                {% endif %}
                            </p>
                            <form action="{% url 'avaliacao' tipo_item=app_name item_id=item_obj.id av_id=obj.id %}" method="post">
                                {% csrf_token %}
                                <input type="text" name="form_comentario" value="true" style="display: none;">
                                <input type="text" name="comentario_id" required value="{{comentario_filho.id}}" style="display:none;">
                                <button type="submit" name='curtir' class="botao-avaliacao like"><i class="fa fa-thumbs-up"></i> Like</button>
                            </form>
                        </td>
                    </tr>
                </table>
            </div>
            {% endfor %}
        {% elif app_name == 'serie' %}
            {% for comentario_filho in comentario.comentarioserie_set.all %}
            <div class="comentarios-avaliacao" style="width: 80%; padding-left: 20px; background-color: rgb(236, 213, 213);">
                <table style="width: 100%; padding-left: 20px;">
                    <tr>
                        <td>
                            <p style="padding:10px 0px 0px; margin: 0px;">
                            <a href="{% url 'usuario' pk=comentario_filho.user_id.id %}" style="text-decoration: none;">
                                @{{comentario_filho.user_id.username}}</a>: <b>{{comentario_filho.texto}}</b>
                            </p>
                        </td>
                        <td style="float: right;">
                            <p>
                                Likes: 
                                {% if app_name == 'filme' %}
                                <b>{{comentario_filho.likecomentariofilme_set.all.count}}</b>
                                {% elif app_name == 'livro' %}
                                <b>{{comentario_filho.likecomentariolivro_set.all.count}}</b>
                                {% elif app_name == 'serie' %}
                                <b>{{comentario_filho.likecomentarioserie_set.all.count}}</b>
                                {% endif %}
                            </p>
                            <form action="{% url 'avaliacao' tipo_item=app_name item_id=item_obj.id av_id=obj.id %}" method="post">
                                {% csrf_token %}
                                <input type="text" name="form_comentario" value="true" style="display: none;">
                                <input type="text" name="comentario_id" required value="{{comentario_filho.id}}" style="display:none;">
                                <button type="submit" name='curtir' class="botao-avaliacao like"><i class="fa fa-thumbs-up"></i> Like</button>
                            </form>
                        </td>
                    </tr>
                </table>
            </div>
        {% endfor %}
        {% endif %}
        {% endfor %}

        <script src="{% static 'js/avaliacao.js'%}"></script>

    </section>
</div>
{% endblock %}

src/avaliacoes/templates/avaliacoes.html
<div class="item-box" style="margin-top: 10px; min-height: 50px;" onclick="location.href={% url '' %}">
    <table style="width: 100%;">
        <tr>
            <td style="width: 50px; text-align: center; padding: 10px;">
                <a href="{% url 'avaliacao' tipo_item=avaliacao.item.tipo_item item_id=avaliacao.item.id av_id=avaliacao.id %}" style="text-decoration: none; color:black;">
                    {% if avaliacao.item.tipo_item == 'filme' %}
                    <i class="fas fa-film fa-3x"></i>
                    {% elif avaliacao.item.tipo_item == 'livro' %}
                    <i class="fas fa-book fa-3x"></i>
                    {% elif avaliacao.item.tipo_item == 'serie' %}
                    <i class="fas fa-theater-masks fa-3x"></i>
                    {% endif %}
                    <br><b>{{avaliacao.item.tipo_item}}</b>
                </a>
            </td>
            <td class="coluna-validar" style="padding-left: 15px;width: 40%;">
                <h1 style="margin:0px; margin-bottom:5px; font-size: 38px;">{{avaliacao.item.titulo}}</h1>
                <span style="padding-top:15px;">{{avaliacao.item.categoria}}</span>
            </td>
            <td class="coluna-validar" style="padding-left: 15px; width: auto;">
                <p>Comentário: {{avaliacao.avaliacao}}</p>
            </td>
        </tr>
    </table>
</div>

src/avaliacoes/templates/avaliacoes_item.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="wrapper">
    <section class="main-container">

    </section>
</div>
{% endblock %}

src/avaliacoes/templates/avaliar_item.html
{% extends 'base_item.html' %}

{% load static %}

{% load bootstrap4 %}

{% block content %}
<div class="wrapper">
  <section class="main-container" style="background-color: rgb(0, 0, 0);">
    <div class="fazer-avaliacao" style="background-color: rgb(184, 111, 190)">
      <form action="{% url 'avaliar_item' tipo_item=app_name item_id=obj.id  %}" method="post" enctype="multipart/form-data" class="login100-form validate-form form">
        {% csrf_token %}
        <h1 style="text-align: center; color:rgb(34, 34, 34)">Avaliar {{obj_name}} </h1>
        <h2>Título - {{obj.titulo}}</h2>
        <img src= "/media/{{obj.imagem.thumbnail}}"/>
        <br>
        <br>
        <div>
          <label for="id_avaliacao"><b>Comentário:</b></label> 
            <textarea rows='10' name="avaliacao" maxlength="1500" required id="id_avaliacao" class="comentario" style=" background-color: rgb(189, 189, 189);"></textarea>
            <select name="item" id="id_item" style=" display: none;"> 
            <option value="{{obj.id}}" selected>{{obj.id}}</option>   
            </select>

            <select name="user_id" id="id_user_id" style=" display: none;"> 
              <option value="{{user.id}}" selected>{{obj.id}}</option>   
            </select>
            <br>
            <br>
            <br>
            <label for="id_valor"><b>Avaliação:</b></label> 
            
            <select 
            name="valor" required id="id_valor">
            <option value="" selected>---------</option> 
            <option value="0">0</option>   
            <option value="1">1</option>
            <option value="2">2</option>   
            <option value="3">3</option>
            <option value="4">4</option>   
            <option value="5">5</option>
            <option value="6">6</option>   
            <option value="7">7</option>
            <option value="8">8</option>  
            <option value="9">9</option>
            <option value="10">10</option>
          </select>
        </div>  
        <div class="container-login100-form-btn">
         <br>
         <br> 
          <button type="submit" name="avaliar">
            <h2 style="text-align: center">Postar avaliação</h2>
          </button>
        </div>
    </div>
      </form>
  </section>
</div>
{% endblock %}